        .byte   $11,$11,$11,$11,$11,$11,$71,$77,$77,$77,$77,$77,$77,$77,$77,$11
        .byte   $11,$11,$11,$11,$22,$22,$22,$22,$72,$77,$77,$77,$55,$55,$55,$55
        .byte   $55,$55,$55,$55,$d5,$55,$55,$55,$dd,$dd,$dd,$dd,$dd,$dd,$dd,$bb
        .byte   $bb,$bb,$ab,$9b,$9b,$bb,$9b,$db,$dd,$dd,$dd,$dd,$dd,$dd,$dd,$dd
        .byte   $dd,$dd,$9d,$99,$9e,$a9,$dd,$dd,$9d,$99,$99,$9e,$dd,$dd,$dd,$dd
        .byte   $dd,$dd,$dd,$dd,$dd,$dd,$99,$99,$99,$dd,$dd,$dd,$dd,$ad,$99,$99
        .byte   $da,$dd,$dd,$dd,$dd,$dd,$dd,$dd,$dd,$cd,$cc,$cc,$cc,$dd,$dd,$dd
        .byte   $dd,$cd,$cc,$cc,$cc,$dd,$dd,$dd,$dd,$dd,$dd,$dd,$dd,$f7,$77,$77
        .byte   $d7,$dd,$dd,$dd,$dd,$dd,$f7,$77,$77,$d7,$dd,$dd,$dd,$dd,$dd,$dd
        .byte   $bb,$9b,$bb,$bb,$dd,$dd,$dd,$dd,$dd,$dd,$9d,$bb,$bb,$ab,$dd,$dd
        .byte   $dd,$dd,$d9,$bb,$bb,$9b,$bb,$bb,$dd,$dd,$dd,$dd,$dd,$dd,$9d,$db
        .byte   $bb,$be,$dd,$dd,$aa,$aa,$b9,$bb,$bb,$9b,$bb,$bb,$dd,$dd,$dd,$dd
        .byte   $dd,$dd,$9d,$dd,$aa,$da,$cd,$aa,$aa,$ba,$b9,$bb,$bb,$be,$aa,$bb
        .byte   $dd,$dd,$dd,$dd,$dd,$dd,$9b,$ab,$aa,$aa,$aa,$aa,$aa,$9a,$d9,$9d
        .byte   $bb,$db,$bb,$bb,$db,$dd,$dd,$dd,$dd,$bd,$bb,$ad,$fd,$d9,$77,$aa
        .byte   $aa,$ca,$aa,$22,$2d,$aa,$2d,$d2,$2d,$aa,$dd,$dd,$dd,$da,$df,$df
        .byte   $b9,$db,$aa,$aa,$aa,$aa,$aa,$da,$ad,$dd,$bb,$bb,$ca,$ad,$df,$aa
        .byte   $cd,$aa,$ad,$da,$db,$da,$ca,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$dd
        .byte   $aa,$aa,$aa,$aa,$aa,$aa,$aa,$dd,$ad,$aa,$aa,$aa,$aa,$fa,$fa,$f7
        .byte   $dd,$a9,$aa,$ad,$22,$da,$dc,$aa,$ab,$ba,$bb,$dd,$ad,$ba,$ab,$aa
        .byte   $aa,$da,$dc,$bd,$ba,$a9,$ab,$da,$ab,$aa,$aa,$aa,$aa,$b7,$77,$99
        .byte   $77,$eb,$bb,$aa,$aa,$aa,$aa,$aa,$aa,$a9,$aa,$aa,$aa,$a9,$da,$aa
        .byte   $da,$ad,$ad,$9a,$da,$da,$aa,$aa,$aa,$aa,$4a,$b4,$bb,$b9,$7e,$77
        .byte   $bb,$d9,$ad,$aa,$aa,$aa,$da,$dd,$ab,$aa,$aa,$aa,$aa,$aa,$99,$99
        .byte   $3b,$39,$7b,$77,$bb,$a9,$da,$aa,$9a,$b7,$db,$dd,$7a,$97,$dd,$aa
        .byte   $aa,$aa,$44,$24,$3b,$39,$7b,$77,$fb,$29,$af,$aa,$97,$77,$dd,$aa
        .byte   $bb,$9b,$aa,$aa,$aa,$aa,$99,$b9,$3b,$3f,$7b,$7d,$fb,$29,$da,$aa
        .byte   $9c,$6b,$a6,$aa,$6d,$96,$d6,$aa,$aa,$aa,$4a,$b4,$3c,$3f,$7b,$77
        .byte   $fb,$a9,$aa,$aa,$aa,$bb,$bb,$aa,$ba,$9b,$aa,$aa,$aa,$aa,$ac,$c4
        .byte   $3b,$ec,$7b,$77,$ff,$aa,$ac,$aa,$aa,$bb,$bb,$9a,$99,$ab,$aa,$aa
        .byte   $aa,$aa,$aa,$cc,$bd,$bb,$bb,$ab,$ac,$ca,$aa,$aa,$aa,$aa,$dc,$aa
        .byte   $d9,$ac,$aa,$aa,$bb,$bb,$bb,$bb